#!/usr/bin/env python3
"""
Phase 2 Generator: Create corpus_v2 from scenario_space_v1
Simple, direct approach without complex templating
"""

import sys
import csv
from pathlib import Path
import pandas as pd

REPO_ROOT = Path(__file__).parent.parent.parent
SCENARIOS_DIR = REPO_ROOT / "scenarios"
MANIFEST_FILE = SCENARIOS_DIR / "scenario_space_v1" / "manifest_candidates.csv"
DATA_DIR = REPO_ROOT / "data"

def generate_settings_simple(row: dict, profile_id: str = "TP01") -> str:
    """Generate simple .settings file"""
    
    candidate_id = row['candidate_id']
    map_id = row['map_id']
    n_hosts = int(row['n_hosts'])
    end_time = int(row['end_time_s'])
    rng_seed = int(row['rng_seed'])
    transmit_range = int(row['transmit_range_m'])
    buffer_size = row['buffer_size']
    movement_model = row['movement_model']
    
    # Map configurations (hardcoded from audit)
    map_configs = {
        'HelsinkiDowntown': {'world_x': 4465, 'world_y': 3185, 'map_file': 'data/HelsinkiDowntown/roads.wkt'},
        'KumpulaCampus': {'world_x': 1955, 'world_y': 1465, 'map_file': 'data/KumpulaCampus/roads.wkt'},
        'ManhattanMidtownGrid': {'world_x': 2120, 'world_y': 1986, 'map_file': 'data/ManhattanMidtownGrid/roads.wkt'},
        'NuuksioSparseTrails': {'world_x': 7911, 'world_y': 7245, 'map_file': 'data/NuuksioSparseTrails/roads.wkt'},
        'HelsinkiDisrupted': {'world_x': 4465, 'world_y': 3185, 'map_file': 'data/HelsinkiDisrupted/roads.wkt'},
        'KallioCommunityCompact': {'world_x': 1800, 'world_y': 1350, 'map_file': 'data/KallioCommunityCompact/roads.wkt'},
    }
    
    if map_id not in map_configs:
        raise ValueError(f"Unknown map: {map_id}")
    
    cfg = map_configs[map_id]
    world_x = cfg['world_x']
    world_y = cfg['world_y']
    map_file = cfg['map_file']
    
    # Traffic profiles
    profiles = {
        'TP01': {'interval': '60,120', 'size': '50k,150k', 'ttl': 7200, 'name': 'Baseline'},
        'TP02': {'interval': '300,600', 'size': '10k,50k', 'ttl': 7200, 'name': 'LowLoad'},
        'TP03': {'interval': '30,60', 'size': '5k,20k', 'ttl': 3600, 'name': 'ManySmall'},
        'TP04': {'interval': '300,600', 'size': '500k,1000k', 'ttl': 14400, 'name': 'FewLarge'},
        'TP05': {'interval': '10,30', 'size': '100k,200k', 'ttl': 600, 'name': 'RealTime'},
        'TP06': {'interval': '600,1200', 'size': '50k,100k', 'ttl': 86400, 'name': 'DelayTolerant'},
    }
    
    if profile_id not in profiles:
        profile_id = 'TP01'
    
    prof = profiles[profile_id]
    
    # Build settings content
    content = f"""# corpus_v2: {candidate_id} + {profile_id}_{prof['name']}
# Generated by: phase2_generator.py
# Map: {map_id} | Movement: {movement_model} | Hosts: {n_hosts}

Scenario.name = CV2_{candidate_id}_{profile_id}
Scenario.simulateConnections = true
Scenario.updateInterval = 0.1
Scenario.endTime = {end_time}

MovementModel.rngSeed = {rng_seed}
MovementModel.worldSize = {world_x}, {world_y}

MapBasedMovement.nrofMapFiles = 1
MapBasedMovement.mapFile1 = {map_file}

# Network
Group.bufferSize = {buffer_size}
Group.nrofInterfaces = 1
Group.interface1 = bt0
bt0.type = SimpleBroadcastInterface
bt0.transmitSpeed = 1M
bt0.transmitRange = {transmit_range}
Group.msgTtl = {prof['ttl']}

# Movement
Group.movementModel = {movement_model}
Group.speed = 0.5, 2.0
Group.waitTime = 0, 600

# Hosts
Scenario.nrofHostGroups = 1
Group1.groupID = a
Group1.nrofHosts = {n_hosts}
Group1.movementModel = {movement_model}
Group1.speed = 0.5, 2.0
Group1.waitTime = 0, 600
Group1.bufferSize = {buffer_size}
Group1.router = EpidemicRouter
Group1.nrofInterfaces = 1
Group1.interface1 = bt0

# Traffic Profile: {profile_id}
Events.nrof = 1
Events1.class = MessageEventGenerator
Events1.interval = {prof['interval']}
Events1.size = {prof['size']}
Events1.hosts = 0, {n_hosts-1}
Events1.prefix = M

# Reports
Report.nrofReports = 2
Report.reportDir = reports/
Report.report1 = MessageStatsReport
Report.report2 = ContactTimesReport
"""
    
    return content


def main():
    print("[Phase 2] Generating corpus_v2...")
    
    # Load manifest
    df = pd.read_csv(MANIFEST_FILE)
    print(f"Loaded {len(df)} candidates")
    
    # Create output directory
    corpus_v2_dir = SCENARIOS_DIR / "corpus_v2"
    corpus_v2_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate settings files
    manifest_out = []
    created = 0
    failed = 0
    
    profiles = ['TP01', 'TP02', 'TP03', 'TP04', 'TP05', 'TP06']
    
    for idx, row in df.iterrows():
        candidate_id = row['candidate_id']
        map_id = row['map_id']
        
        # Create per-map directory
        map_dir = corpus_v2_dir / f"map_{map_id}"
        map_dir.mkdir(parents=True, exist_ok=True)
        
        for profile in profiles:
            try:
                content = generate_settings_simple(row.to_dict(), profile)
                filename = f"CV2_{candidate_id}_{profile}.settings"
                filepath = map_dir / filename
                
                with open(filepath, 'w') as f:
                    f.write(content)
                
                manifest_out.append({
                    'scenario_name': f"CV2_{candidate_id}_{profile}",
                    'candidate_id': candidate_id,
                    'profile': profile,
                    'map_id': map_id,
                    'movement_model': row['movement_model'],
                    'n_hosts': row['n_hosts'],
                    'settings_file': str(filepath.relative_to(SCENARIOS_DIR)),
                })
                
                created += 1
                
            except Exception as e:
                print(f"  ERROR {candidate_id} + {profile}: {e}")
                failed += 1
        
        if (idx + 1) % 500 == 0:
            print(f"  Processed {idx+1}/{len(df)}... Created: {created}, Failed: {failed}")
    
    # Save manifest
    manifest_df = pd.DataFrame(manifest_out)
    manifest_csv = corpus_v2_dir / "manifest.csv"
    manifest_df.to_csv(manifest_csv, index=False)
    
    print(f"\n✅ DONE")
    print(f"  Created: {created} .settings files")
    print(f"  Failed: {failed}")
    print(f"  corpus_v2 location: {corpus_v2_dir}")
    print(f"  Manifest: {manifest_csv}")


if __name__ == '__main__':
    main()
